# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Automation Containerize

on:
  push:
    branches:
      - develop

env:
  IMAGE_TAG: latest
  IMAGE_NAME: pukdbros/simple-boilerplate-app

jobs:
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-boilerplate-app:latest

  deploy_to_k8s:
    name: Deploy to K8S
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: connect K8S Cluster
      run: ${{ secrets.KUBE_CONFIG }}
    - name: Modify Manifest
      run: |
        export NAME_WITH_TAG=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        yq -i '.spec.template.spec.containers[0].image=strenv(NAME_WITH_TAG)' ./manifest/development.yaml
    - name: Deploy
      run: kubectl apply -f ./manifest/.
